plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
}

android {
    namespace 'com.dsann.phonebridge.hfpdiagnostic'
    compileSdk 35

    defaultConfig {
        applicationId 'com.dsann.phonebridge.hfpdiagnostic'
        minSdk 23
        targetSdk 35
        versionCode 1
        versionName '0.1.0'
    }

    kotlinOptions {
        jvmTarget = '17'
    }
}

kotlin {
    jvmToolchain(17)
}
