plugins {
    id 'com.android.application'
}

android {
    namespace 'com.dsann.batterymonitor'
    compileSdk 36

    defaultConfig {
        applicationId 'com.dsann.batterymonitor.tab'
        minSdk 23
        targetSdk 36
        versionCode 1
        versionName '1.0-tablet'
    }

    buildTypes {
        release {
            minifyEnabled true
            shrinkResources true
            signingConfig signingConfigs.debug
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt')
        }
    }
}
