plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
}

android {
    namespace 'com.dsann.phonebridge'
    compileSdk 35

    defaultConfig {
        applicationId 'com.dsann.phonebridge'
        minSdk 23
        targetSdk 28
        versionCode 1
        versionName '0.1.0'

        externalNativeBuild {
            cmake {
                cppFlags '-std=c++11'
            }
        }
    }

    externalNativeBuild {
        cmake {
            path file('src/main/cpp/CMakeLists.txt')
        }
    }
}

kotlin {
    jvmToolchain(8)
}
